<?php

namespace Tests\Feature;

use App\Models\Meeting;
use App\Models\MeetingAttendance;
use App\Models\Setting;
use App\Models\User;
use App\Models\ZoomMeeting;
use App\Services\ZoomService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Mockery\MockInterface;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class BusinessProcessTest extends TestCase
{
    use RefreshDatabase;

    public function test_guest_can_submit_attendance_via_public_link()
    {
        // 1. Setup Meeting
        $user = User::factory()->create();
        $meeting = Meeting::factory()->create([
            'organizer_id' => $user->id,
        ]);
        // UUID should be auto-generated by boot
        $this->assertNotNull($meeting->uuid);

        // 2. Submit Attendance
        $response = $this->postJson("/api/public/meetings/{$meeting->uuid}/attendance", [
            'name' => 'Budi Tamu',
            'email' => 'budi@instansi.go.id',
            'agency' => 'Kemenkeu',
            'signature_path' => 'base64sig...',
        ]);

        // 3. Assertions
        $response->assertCreated();
        $this->assertDatabaseHas('meeting_attendances', [
            'meeting_id' => $meeting->id,
            'name' => 'Budi Tamu',
            'agency' => 'Kemenkeu',
        ]);
    }

    public function test_authenticated_user_can_view_attendance_list()
    {
        // Create permissions
        $role = Role::create(['name' => 'admin']);
        $permission = Permission::create(['name' => 'view meetings']);
        $user = User::factory()->create();
        $user->givePermissionTo('view meetings');

        $meeting = Meeting::factory()->create(['organizer_id' => $user->id]);
        MeetingAttendance::create([
            'meeting_id' => $meeting->id,
            'name' => 'Guest 1',
        ]);

        $this->actingAs($user);

        // Ensure policy allows 'view'. MeetingPolicy::view usually checks if user is organizer or participant.
        // We set organizer_id so it should pass.
        // But route might have middleware('permission:view meetings')?
        // Checked api.php: Route::get... ->middleware('permission:view meetings');

        $response = $this->getJson("/api/meetings/{$meeting->id}/attendances");

        $response->assertOk()
            ->assertJsonCount(1, 'data')
            ->assertJsonFragment(['name' => 'Guest 1']);
    }

    public function test_zoom_sync_fetches_recordings_and_summary()
    {
        // 1. Setup Data
        Permission::create(['name' => 'manage meetings']);
        Permission::create(['name' => 'edit meetings']); // Route middleware requires this
        $user = User::factory()->create();
        $user->givePermissionTo(['manage meetings', 'edit meetings']);

        $setting = Setting::factory()->create([
            'name' => 'zoom_account_1',
            'payload' => [
                'client_id' => 'cid',
                'client_secret' => 'sec',
                'account_id' => 'acc',
            ],
        ]);

        $meeting = Meeting::factory()->create(['organizer_id' => $user->id]);
        $zoomMeeting = ZoomMeeting::create([
            'meeting_id' => $meeting->id,
            'zoom_id' => '123456',
            'uuid' => 'zUuid',
            'setting_id' => $setting->id,
            // required fields from factory usually, but manual create implies minimal
            'host_id' => 'host',
            'type' => 2,
            'start_time' => now(),
            'duration' => 60,
            'settings' => [],
        ]);

        // 2. Mock ZoomService
        $this->mock(ZoomService::class, function (MockInterface $mock) {
            $mock->shouldReceive('setCredentials')->once();

            // Helper to create a response object
            $createResponse = function ($data) {
                return new \Illuminate\Http\Client\Response(
                    new \GuzzleHttp\Psr7\Response(200, [], json_encode($data))
                );
            };

            // Mock getRecordings
            $mock->shouldReceive('getRecordings')
                ->with('123456')
                ->once()
                ->andReturn($createResponse([
                    'share_url' => 'https://zoom.us/rec/play/xyz',
                    'password' => 'secret123',
                ]));

            // Mock getMeetingSummary
            $mock->shouldReceive('getMeetingSummary')
                ->with('123456')
                ->once()
                ->andReturn($createResponse([
                    'summary_details' => 'Meeting went well.',
                ]));
        });

        // 3. Call Sync Endpoint using Dependency Injection resolution for Controller
        // Important: Since we mocked ZoomService in container, the controller should pick it up.
        // Controller accesses $this->zoomService injected in constructor?
        // Wait, ZoomController injects ZoomService. The mock should work if done before request.

        $this->actingAs($user);
        $response = $this->getJson('/api/zoom/meetings/123456/sync');

        // 4. Verification
        $response->assertOk();

        $zoomMeeting->refresh();
        $this->assertEquals('https://zoom.us/rec/play/xyz', $zoomMeeting->recording_play_url);
        $this->assertEquals('secret123', $zoomMeeting->recording_passcode);
        $this->assertEquals('Meeting went well.', $zoomMeeting->summary_content);
    }
}
