services:
  nginx:
    image: nginx:alpine
    container_name: bpkad-zoom-laravel-be-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dokploy-network

networks:
  dokploy-network:
    driver: overlay
