services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bpkad-zoom-laravel-be-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app-code:/var/www/html
    networks:
      - bpkad-network
    env_file:
      - ./db.env

  nginx:
    image: nginx:alpine
    container_name: bpkad-zoom-laravel-be-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - app-code:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bpkad-network
    depends_on:
      - app

  db:
    image: postgres:13-alpine
    container_name: bpkad-zoom-laravel-be-db
    restart: unless-stopped
    env_file:
      - ./db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bpkad-network

networks:
  bpkad-network:
    driver: bridge

volumes:
  app-code:
    driver: local
  postgres-data:
    driver: local
